fn exception_ex() {
    let x = 5;
    let y = &mut x;//cannot borrow `x` as mutable
}


fn main(){
    
}
